### ISSUE TITLE
pre_trained models

### ISSUE THREAD

**Issue by ManyToms888** [silence-tang/ArtNeRF#1]
Hi dear, is it posible for you guys to provide the pretrained models? Thanks very much! Also, I strictly followed the readme file and the constructions given, but still found some bugs. Anyway, I have tried to fix them by myself, but the final model trained by me is not working properly, so any help or suggestions? Really appreciate it!

**Comment by silence-tang** [comment]
Hi, thanks for your attention! These days I'm a little busy. I will check the code and release the pretrained models later.

**Comment by ManyToms888** [comment]
> Hi, thanks for your attention! These days I'm a little busy. I will check the code and release the pretrained models later.

Sure thing!

**Comment by ManyToms888** [comment]
> Hi, thanks for your attention! These days I'm a little busy. I will check the code and release the pretrained models later.

大佬，我很想复刻artnerf这篇论文的模型，你那边啥时候可以更新一下呢 感谢！

**Comment by silence-tang** [comment]
readme更新了，预训练模型也给出来了。你重新克隆一下项目，然后根据readme配置一下。推理就是用renderxxx.py，应该能直接运行。训练的话我这边数据集删了，没法验证还能不能运行了，你如果有兴趣可以自己测试一下，有问题继续交流。

**Comment by MengqianCao** [comment]
你好！我尝试复现，发现models文件夹缺少siren.py和encoder.py，请问方便传一下这两个文件吗，万分感谢！！！

**Comment by ManyToms888** [comment]
> readme更新了，预训练模型也给出来了。你重新克隆一下项目，然后根据readme配置一下。推理就是用renderxxx.py，应该能直接运行。训练的话我这边数据集删了，没法验证还能不能运行了，你如果有兴趣可以自己测试一下，有问题继续交流。

十分感谢更新！我在尝试跑render_image.py的时候发现以下错误：ImportError: cannot import name 'encoder' from 'models' 大佬有时间可以上传一下不，谢谢

**Comment by silence-tang** [comment]
> 你好！我尝试复现，发现models文件夹缺少siren.py和encoder.py，请问方便传一下这两个文件吗，万分感谢！！！

你好，上传了，里面有些import和load模型的语句可能需要你根据自己的绝对路径重写一下。

**Comment by silence-tang** [comment]
> > readme更新了，预训练模型也给出来了。你重新克隆一下项目，然后根据readme配置一下。推理就是用renderxxx.py，应该能直接运行。训练的话我这边数据集删了，没法验证还能不能运行了，你如果有兴趣可以自己测试一下，有问题继续交流。
> 
> 十分感谢更新！我在尝试跑render_image.py的时候发现以下错误：ImportError: cannot import name 'encoder' from 'models' 大佬有时间可以上传一下不，谢谢

不客气，已经上传了encoder.py。可能你需要根据自己的绝对路径重写一下一些import和load model的语句。此外，你需要下载一下ArtNeRF-main/vgg_base文件夹的东西

**Comment by silence-tang** [comment]
> 你好！我尝试复现，发现models文件夹缺少siren.py和encoder.py，请问方便传一下这两个文件吗，万分感谢！！！

然后你再下载一下ArtNeRF-main/vgg_base文件夹的东西

**Comment by ManyToms888** [comment]
> > > readme更新了，预训练模型也给出来了。你重新克隆一下项目，然后根据readme配置一下。推理就是用renderxxx.py，应该能直接运行。训练的话我这边数据集删了，没法验证还能不能运行了，你如果有兴趣可以自己测试一下，有问题继续交流。
> > 
> > 
> > 十分感谢更新！我在尝试跑render_image.py的时候发现以下错误：ImportError: cannot import name 'encoder' from 'models' 大佬有时间可以上传一下不，谢谢
> 
> 不客气，已经上传了encoder.py。可能你需要根据自己的绝对路径重写一下一些import和load model的语句。此外，你需要下载一下ArtNeRF-main/vgg_base文件夹的东西

十分感谢！
